# Generated by Django 3.1.6 on 2021-02-02 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('author',
                 models.ForeignKey(
                     help_text='Это поле заполняется автоматически',
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='following',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Подписка на автора')),
                ('user', models.ForeignKey(
                    help_text='Это поле заполняется автоматически',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='follower', to=settings.AUTH_USER_MODEL,
                    verbose_name='Пользователь')),
            ],
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'),
                                               name='unique_object'),
        ),
    ]
